apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-gpu
      image: 10.0.68.36/library/caffe:1.0-gpu
      resources:
        limits:
          nvidia.com/gpu: 4 # requesting 2 GPUs
